# Generated by Django 4.2.5 on 2023-09-22 21:00

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.SlugField(blank=True, null=True)),
                ('password', models.CharField(max_length=150)),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_doctor', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Government',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('ar_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='المحافظة')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='SkillType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ar_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع المهارات')),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ar_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='التخصص')),
                ('icon', models.ImageField(default='specilizations/stethoscope-alt.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ar_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='الجامعة')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ar_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='المنطقة')),
                ('government', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.government')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ar_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='المهارات')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='media/doctors/')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.skilltype')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('government', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.government', verbose_name='المحافظة')),
                ('phone', models.ManyToManyField(blank=True, to='accounts.phone')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.state', verbose_name='المنطقة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ar_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='الكلية')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.university')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='users/logo.webp', null=True, upload_to=accounts.models.imagesave, verbose_name='صورة شخصية')),
                ('coverletter', models.TextField(null=True, verbose_name='تفاصيل')),
                ('bio', models.CharField(max_length=255, null=True, verbose_name='عنوان سيرة ذاتية')),
                ('is_completed', models.BooleanField(default=False)),
                ('skills', models.ManyToManyField(to='accounts.skill', verbose_name='المهارات')),
                ('specialization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.specialization', verbose_name='التخصص')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.ManyToManyField(blank=True, to='accounts.phone'),
        ),
    ]
