# Generated by Django 4.2.5 on 2023-09-20 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_is_opned_clinic_is_opened'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinic',
            old_name='phone',
            new_name='phones',
        ),
    ]
