# Generated by Django 4.2.5 on 2023-09-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_timetable_remove_patient_image_reservasion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='time_tables',
            field=models.ManyToManyField(blank=True, to='accounts.timetable'),
        ),
    ]
