# Generated by Django 4.2.5 on 2023-09-23 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailLocation', models.CharField(blank=True, max_length=555, null=True, verbose_name='العنوان المفصل')),
                ('mapsLocation', models.CharField(blank=True, max_length=555, null=True, verbose_name='العنوان علي خرائط جوجل')),
                ('price', models.FloatField(blank=True, null=True)),
                ('is_opened', models.BooleanField(default=False)),
                ('last_opened', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor')),
                ('government', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.government', verbose_name='المحافظة')),
                ('phones', models.ManyToManyField(blank=True, to='accounts.phone')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.state', verbose_name='المنطقة')),
            ],
        ),
        migrations.CreateModel(
            name='Reservasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Reservasion Date')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('is_full', models.BooleanField(default=False)),
                ('reservasions', models.ManyToManyField(to='clinic.reservasion')),
            ],
        ),
        migrations.AddField(
            model_name='clinic',
            name='time_tables',
            field=models.ManyToManyField(blank=True, to='clinic.timetable'),
        ),
    ]
