# Generated by Django 4.2.5 on 2023-09-11 16:51

import Auth.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Government',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='المحافظة')),
            ],
        ),
        migrations.CreateModel(
            name='SkillType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='المنطقة')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.SlugField(blank=True, null=True)),
                ('password', models.CharField(max_length=150)),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_doctor', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='التخصص')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Auth.faculty', verbose_name='الكلية')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Auth.university', verbose_name='الجامعة')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('from_date', models.DateTimeField(null=True)),
                ('to_date', models.DateTimeField(null=True)),
                ('certificate', models.FileField(upload_to='media/doctors/')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Auth.skilltype')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='users/logo.png', null=True, upload_to=Auth.models.imagesave, verbose_name='صورة شخصية')),
                ('government', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Auth.government', verbose_name='المحافظة')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Auth.state', verbose_name='المنطقة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='users/logo.webp', null=True, upload_to=Auth.models.imagesave, verbose_name='صورة شخصية')),
                ('coverletter', models.TextField(null=True, verbose_name='تفاصيل')),
                ('bio', models.CharField(blank=True, max_length=255, verbose_name='عنوان سيرة ذاتية')),
                ('skills', models.ManyToManyField(to='Auth.skill', verbose_name='المهارات')),
                ('specialization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Auth.specialization', verbose_name='التخصص')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailLocation', models.CharField(max_length=555, verbose_name='العنوان المفصل')),
                ('mapsLocation', models.CharField(blank=True, max_length=555, null=True, verbose_name='العنوان علي خرائط جوجل')),
                ('price', models.FloatField(verbose_name='سعر الكشف')),
                ('is_opned', models.BooleanField(default=False, verbose_name='العيادة مفتوحة')),
                ('last_opened', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.doctor')),
                ('government', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Auth.government', verbose_name='المحافظة')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Auth.state', verbose_name='المنطقة')),
            ],
        ),
    ]
