# Generated by Django 4.2.5 on 2023-09-14 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='date',
        ),
        migrations.AlterField(
            model_name='skill',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='media/doctors/'),
        ),
    ]
