# Generated by Django 4.2.5 on 2023-09-11 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='bio',
            field=models.CharField(max_length=255, null=True, verbose_name='عنوان سيرة ذاتية'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Auth.specialization', verbose_name='التخصص'),
        ),
    ]
