# Generated by Django 4.2.3 on 2023-09-10 15:17

import Auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default='users/logo.webp', null=True, upload_to=Auth.models.imagesave, verbose_name='صورة شخصية'),
        ),
    ]
