# Generated by Django 4.2.5 on 2023-09-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='phone',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
