# Generated by Django 4.2.5 on 2023-09-14 01:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_remove_skill_date_alter_skill_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
