# Generated by Django 4.2.5 on 2023-09-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_doctor_is_completed_alter_doctor_specialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='to_date',
        ),
        migrations.AddField(
            model_name='skill',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
