# Generated by Django 4.2.5 on 2023-09-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_skill_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialization',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='university',
        ),
        migrations.AlterField(
            model_name='specialization',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
