# Generated by Django 4.2.5 on 2023-09-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_remove_specialization_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='ar_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الكلية'),
        ),
        migrations.AddField(
            model_name='skill',
            name='ar_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المهارات'),
        ),
        migrations.AddField(
            model_name='skilltype',
            name='ar_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع المهارات'),
        ),
        migrations.AddField(
            model_name='specialization',
            name='ar_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='التخصص'),
        ),
        migrations.AddField(
            model_name='state',
            name='ar_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المنطقة'),
        ),
        migrations.AddField(
            model_name='university',
            name='ar_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الجامعة'),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
