# Generated by Django 4.2.5 on 2023-09-12 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_remove_skill_from_date_remove_skill_to_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialization',
            name='university',
        ),
        migrations.AddField(
            model_name='faculty',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Auth.university'),
            preserve_default=False,
        ),
    ]
