# Generated by Django 4.2.5 on 2023-09-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_faculty_ar_name_skill_ar_name_skilltype_ar_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
