# Generated by Django 4.2.5 on 2023-09-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_specialization_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='icon',
            field=models.ImageField(default='imgs/specilizations/stethoscope-alt.png', upload_to=''),
        ),
    ]
